language: node_js

node_js:
  - "node"

branches:
  only:
    - master

cache:
  bundler: true
  yarn: true
  directories:
    - node_modules

before_install:
  - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc

before_script:
  - yarn clean

script:
  - yarn lint
  - yarn test

after_success:
  - yarn semantic-release

notifications:
  email: false
